### ISSUE TITLE
Bumper issue Vlasiator Summer of Debugging 2016

### ISSUE THREAD

**Issue by ykempf** [fmihpc/vlasiator#274]
This issue lists the series of bugs fixed and improvements made as a result of the debugging campaign in summer 2016.

It will include a checklist here before all mergers are made and possible combinations of subsets could be tested and reported here.
- [x] #275 Upwinding is done with the whistler speed, it shouldn't
- [x] #269 Fix acceleration substep dt
- [x] #270 Acc map order is globally the same ­-- This created a signal propagating one cell per step only in one direction.
- [x] #276 Update moments during acceleration subcycling
- [x] #277 Fix test_fp to be runnable and used in the testpackage again
- [ ] #278 Include some form of Dispersion tests in the testpackage
- [ ] #279 Improved coupling  fieldsolver - ion moments

**Comment by ursg** [comment]
2016 is very much over now and the issues have been carried forward.
